id: I3C38D4FC
source: https://www.lotsawahouse.org
source_file: null
initial_creation_type: input
imported: '2022-06-17T12:33:01.309902'
last_modified: '2022-06-17T12:33:01.309909'
parser: null
source_metadata:
  title: Literary Theory
  language: bo
  description: 'Texts related to the various aspects of literary composition:'
  volume:
    f3BF2:
      title: Notes from Miscellaneous Writings
      base_file: f3BF2.txt
      order: 1
      parent: Exposition
    fDF8D:
      title: On Literary Composition
      base_file: fDF8D.txt
      order: 2
      parent: Literary Composition
    fFF0B:
      title: Types of Spiritual Song
      base_file: fFF0B.txt
      order: 3
      parent: Spiritual Songs
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
